AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  #Create Table
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "EmployeeId"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "EmployeeId"
          KeyType: "HASH"
      TableName: "Employee"
      BillingMode: "PAY_PER_REQUEST"